### ISSUE TITLE
关于我fork后在主页完全没有活跃度的提问

### ISSUE THREAD

**Issue by SilingRWBY** [XC0703/autocommit-robot#1]
作者好，我想问一下我设置了自己的token，但是每天的自动运行后，我的主页活跃度却完全没有。
是否是robot.yml里的auther项和email项都需要设置成自己git的账号对应的值呢？相应项是否可以用${{ secrets.对应的Repository secrets名 }}代替？

**Comment by XC0703** [comment]
是的，设置成你自己的git的账号对应的值试一下吧


Sunshine&nbsp;Teenage
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XC0703/autocommit-robot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月19日(星期二) 下午4:22
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[XC0703/autocommit-robot] 关于我fork后在主页完全没有活跃度的提问 (Issue #1)





 
作者好，我想问一下我设置了自己的token，但是每天的自动运行后，我的主页活跃度却完全没有。
 是否是robot.yml里的auther项和email项都需要设置成自己git的账号对应的值呢？相应项是否可以用${{ secrets.对应的Repository secrets名 }}代替？

**Comment by SilingRWBY** [comment]
哦，还以一点，我在直接编辑.yml后，在action日志那里看到错误显示为
“Error: .github#L1
No event triggers defined in `on`”
完全不懂啥意思

**Comment by SilingRWBY** [comment]
今天的自动计划成功了，同时主页活跃也被打上了标记，看来确实需要修改.yml文件的三个项为自己对应的。
**再次感谢！**
